#!/usr/bin/env python3
"""Merge all greedy problem data sources into one deduplicated CSV."""
import csv
import re

OUTPUT = "/home/rashid/Project/dsa-mastery/greedy/all_greedy_problems.csv"
EXISTING_FILES = [
    "/home/rashid/Project/dsa-mastery/greedy_problems.csv",
    "/home/rashid/Project/dsa-mastery/greedy_problems_comprehensive.csv",
    "/tmp/leetcode_greedy.csv",
]

def read_csv(path):
    rows = []
    with open(path, newline='', encoding='utf-8') as f:
        reader = csv.reader(f)
        for row in reader:
            if not row or len(row) < 6:
                continue
            if row[0] == 'PLATFORM' or row[0].startswith('Platform'):
                continue
            # Normalize to 6 columns
            if len(row) > 6:
                row = row[:6]
            rows.append(row)
    return rows

all_rows = {}
for fp in EXISTING_FILES:
    try:
        for r in read_csv(fp):
            url = r[3].strip()
            if url and url not in all_rows:
                all_rows[url] = r
    except FileNotFoundError:
        pass

ATCODER = [
    ["AtCoder","Greedy","B. Golden Coins","https://atcoder.jp/contests/abc160/tasks/abc160_b","Easy","Greedy coin change"],
    ["AtCoder","Greedy","A. Painting","https://atcoder.jp/contests/keyence2020/tasks/keyence2020_a","Easy","Greedy area calculation"],
    ["AtCoder","Greedy","B. Minor Change","https://atcoder.jp/contests/abc172/tasks/abc172_b","Easy","Character comparison"],
    ["AtCoder","Greedy","B. Slimes","https://atcoder.jp/contests/abc248/tasks/abc248_b","Easy","Repeated multiplication"],
    ["AtCoder","Greedy","B. Christmas Eve Eve","https://atcoder.jp/contests/abc115/tasks/abc115_b","Easy","Sort & pick max"],
    ["AtCoder","Greedy","B. Factorial Yen Coin","https://atcoder.jp/contests/abc208/tasks/abc208_b","Easy","Greedy subtraction"],
    ["AtCoder","Greedy","B. 1D Keyboard","https://atcoder.jp/contests/abc373/tasks/abc373_b","Easy","Greedy position tracking"],
    ["AtCoder","Greedy","B. Easy Linear Programming","https://atcoder.jp/contests/abc167/tasks/abc167_b","Easy","Greedy case analysis"],
    ["AtCoder","Greedy","B. Magic 2","https://atcoder.jp/contests/m-solutions2020/tasks/m_solutions2020_b","Easy","Greedy operations"],
    ["AtCoder","Greedy","B. Gentle Pairs","https://atcoder.jp/contests/abc187/tasks/abc187_b","Easy","Greedy slope counting"],
    ["AtCoder","Greedy","C. Fennec vs Monster","https://atcoder.jp/contests/abc153/tasks/abc153_c","Easy","Sort & use special attacks"],
    ["AtCoder","Greedy","C. Step","https://atcoder.jp/contests/abc176/tasks/abc176_c","Easy","Greedy increment"],
    ["AtCoder","Greedy","B. Maximum Sum","https://atcoder.jp/contests/abc096/tasks/abc096_b","Easy","Repeated max operation"],
    ["AtCoder","Greedy","A. Poisonous Cookies","https://atcoder.jp/contests/agc030/tasks/agc030_a","Easy","Greedy eating strategy"],
    ["AtCoder","Greedy","A. Colorful Slimes 2","https://atcoder.jp/contests/agc026/tasks/agc026_a","Easy","Greedy adjacent merge"],
    ["AtCoder","Greedy","C. PC on the Table","https://atcoder.jp/contests/abc297/tasks/abc297_c","Easy","Greedy pattern replacement"],
    ["AtCoder","Greedy","B. Snake Toy","https://atcoder.jp/contests/abc067/tasks/abc067_b","Easy","Sort & select largest"],
    ["AtCoder","Greedy","B. Postdocs","https://atcoder.jp/contests/nomura2020/tasks/nomura2020_b","Easy","Greedy character replacement"],
    ["AtCoder","Greedy","B. Addition and Multiplication","https://atcoder.jp/contests/abc076/tasks/abc076_b","Easy","Greedy arithmetic"],
    ["AtCoder","Greedy","C. Kaprekar Number","https://atcoder.jp/contests/abc192/tasks/abc192_c","Easy","Greedy digit sort"],
    ["AtCoder","Greedy","A. A ↔ BB","https://atcoder.jp/contests/arc136/tasks/arc136_a","Easy","Greedy string reduction"],
    ["AtCoder","Greedy","B. Discord","https://atcoder.jp/contests/abc303/tasks/abc303_b","Easy","Greedy pair counting"],
    ["AtCoder","Greedy","C. Alchemist","https://atcoder.jp/contests/abc138/tasks/abc138_c","Medium","Sort & greedy merge"],
    ["AtCoder","Greedy","C. ABC Tournament","https://atcoder.jp/contests/abc188/tasks/abc188_c","Easy","Tournament bracket greedy"],
    ["AtCoder","Greedy","B. Nice Shopping","https://atcoder.jp/contests/hitachi2020/tasks/hitachi2020_b","Easy","Greedy min-cost combination"],
    ["AtCoder","Greedy","C. T-shirts","https://atcoder.jp/contests/abc332/tasks/abc332_c","Medium","Greedy resource planning"],
    ["AtCoder","Greedy","B. Foreign Exchange","https://atcoder.jp/contests/abc341/tasks/abc341_b","Medium","Greedy currency conversion"],
    ["AtCoder","Greedy","B. A to Z String","https://atcoder.jp/contests/abc053/tasks/abc053_b","Medium","First/last character greedy"],
    ["AtCoder","Greedy","C. Cheese","https://atcoder.jp/contests/abc229/tasks/abc229_c","Medium","Sort by value descending"],
    ["AtCoder","Greedy","C. Friends and Travel costs","https://atcoder.jp/contests/abc203/tasks/abc203_c","Medium","Sort & simulate"],
    ["AtCoder","Greedy","C. Number Place","https://atcoder.jp/contests/abc327/tasks/abc327_c","Medium","Greedy sudoku validation"],
    ["AtCoder","Greedy","D. Brick Break","https://atcoder.jp/contests/abc148/tasks/abc148_d","Medium","Greedy sequence matching"],
    ["AtCoder","Greedy","A. Candy Distribution Again","https://atcoder.jp/contests/agc027/tasks/agc027_a","Medium","Greedy distribution"],
    ["AtCoder","Greedy","A. Dividing a String","https://atcoder.jp/contests/agc037/tasks/agc037_a","Medium","Greedy consecutive char merge"],
    ["AtCoder","Greedy","C. Half and Half","https://atcoder.jp/contests/arc096/tasks/arc096_a","Medium","Greedy combo pricing"],
    ["AtCoder","Greedy","C. Christmas Eve","https://atcoder.jp/contests/abc115/tasks/abc115_c","Medium","Sort & min diff"],
    ["AtCoder","Greedy","C. Build Stairs","https://atcoder.jp/contests/abc136/tasks/abc136_c","Medium","Greedy non-decreasing"],
    ["AtCoder","Greedy","B. Mex Boxes","https://atcoder.jp/contests/keyence2021/tasks/keyence2021_b","Medium","Greedy MEX construction"],
    ["AtCoder","Greedy","B. Increasing Triples","https://atcoder.jp/contests/arc123/tasks/arc123_b","Medium","Greedy triple matching"],
    ["AtCoder","Greedy","C. Energy Drink Collector","https://atcoder.jp/contests/abc121/tasks/abc121_c","Medium","Sort by price ascending"],
    ["AtCoder","Greedy","C. Unification","https://atcoder.jp/contests/abc120/tasks/abc120_c","Medium","Greedy stack elimination"],
    ["AtCoder","Greedy","C. AtCoder Cards","https://atcoder.jp/contests/abc301/tasks/abc301_c","Medium","Greedy character matching"],
    ["AtCoder","Greedy","C. Multiple Gift","https://atcoder.jp/contests/arc088/tasks/arc088_a","Medium","Repeated doubling"],
    ["AtCoder","Greedy","D. Souvenirs","https://atcoder.jp/contests/abc358/tasks/abc358_d","Medium","Sort & greedy matching"],
    ["AtCoder","Greedy","B. Five Dishes","https://atcoder.jp/contests/abc123/tasks/abc123_b","Medium","Greedy time calculation"],
    ["AtCoder","Greedy","A. AtCoder Group Contest","https://atcoder.jp/contests/agc012/tasks/agc012_a","Hard","Sort & pick 2nd largest"],
    ["AtCoder","Greedy","D. Stamp","https://atcoder.jp/contests/abc185/tasks/abc185_d","Hard","Greedy interval covering"],
    ["AtCoder","Greedy","D. Alter Altar","https://atcoder.jp/contests/abc174/tasks/abc174_d","Hard","Greedy swap/count"],
    ["AtCoder","Greedy","C. Bugged","https://atcoder.jp/contests/arc075/tasks/arc075_a","Hard","Sort & sum optimization"],
    ["AtCoder","Greedy","A. Ice Tea Store","https://atcoder.jp/contests/agc019/tasks/agc019_a","Hard","Greedy bulk buying"],
    ["AtCoder","Greedy","B. log","https://atcoder.jp/contests/arc109/tasks/arc109_b","Hard","Greedy bin-packing"],
    ["AtCoder","Greedy","C. When I hit my pocket...","https://atcoder.jp/contests/yahoo-procon2019-qual/tasks/yahoo_procon2019_qual_c","Hard","Greedy pocket strategy"],
    ["AtCoder","Greedy","C. Grand Garden","https://atcoder.jp/contests/abc116/tasks/abc116_c","Hard","Greedy watering"],
    ["AtCoder","Greedy","C. Scc Puzzle","https://atcoder.jp/contests/arc069/tasks/arc069_a","Hard","Greedy pair construction"],
    ["AtCoder","Greedy","C. Mandarin Orange","https://atcoder.jp/contests/abc189/tasks/abc189_c","Hard","Greedy subarray selection"],
    ["AtCoder","Greedy","C. 4-adjacent","https://atcoder.jp/contests/arc080/tasks/arc080_a","Hard","Greedy parity/multiple"],
    ["AtCoder","Greedy","C. Minimization","https://atcoder.jp/contests/arc099/tasks/arc099_a","Hard","Greedy spread minimization"],
    ["AtCoder","Greedy","D. Megalomania","https://atcoder.jp/contests/abc131/tasks/abc131_d","Hard","Sort by deadline"],
    ["AtCoder","Greedy","C. Make a Rectangle","https://atcoder.jp/contests/arc081/tasks/arc081_a","Hard","Greedy pair selection"],
    ["AtCoder","Greedy","C. Streamline","https://atcoder.jp/contests/abc117/tasks/abc117_c","Hard","Sort & remove gaps"],
    ["AtCoder","Greedy","A. Sorted Arrays","https://atcoder.jp/contests/agc013/tasks/agc013_a","Hard","Greedy increasing segments"],
    ["AtCoder","Greedy","A. XOR Circle","https://atcoder.jp/contests/agc035/tasks/agc035_a","Hard","Greedy XOR counting"],
    ["AtCoder","Greedy","C. Hotel","https://atcoder.jp/contests/codefestival-2015-qualb/tasks/codefestival_2015_qualB_c","Hard","Sort by capacity"],
    ["AtCoder","Greedy","D. Choose Me","https://atcoder.jp/contests/abc187/tasks/abc187_d","Hard","Sort by gain descending"],
    ["AtCoder","Greedy","A. Gold and Silver","https://atcoder.jp/contests/arc128/tasks/arc128_a","Hard","Greedy profit calculation"],
    ["AtCoder","Greedy","D. Derangement","https://atcoder.jp/contests/arc082/tasks/arc082_b","Hard","Greedy minimum swap"],
    ["AtCoder","Greedy","B. Abbreviate Fox","https://atcoder.jp/contests/arc108/tasks/arc108_b","Hard","Greedy string removal"],
    ["AtCoder","Greedy","D. Triangles","https://atcoder.jp/contests/abc143/tasks/abc143_d","Hard","Sort & triangle inequality"],
    ["AtCoder","Greedy","C. Exam and Wizard","https://atcoder.jp/contests/keyence2019/tasks/keyence2019_c","Hard","Sort by score difference"],
    ["AtCoder","Greedy","D. Prediction and Restriction","https://atcoder.jp/contests/abc149/tasks/abc149_d","Hard","Greedy win prediction"],
    ["AtCoder","Greedy","D. Chat in a Circle","https://atcoder.jp/contests/abc173/tasks/abc173_d","Hard","Greedy circle arrangement"],
    ["AtCoder","Greedy","C. Go Home","https://atcoder.jp/contests/arc070/tasks/arc070_a","Hard","Greedy cumulative sum"],
    ["AtCoder","Greedy","A. Limited Insertion","https://atcoder.jp/contests/agc032/tasks/agc032_a","Hard","Reverse greedy construction"],
    ["AtCoder","Greedy","A. Simple Calculator","https://atcoder.jp/contests/agc008/tasks/agc008_a","Hard","Greedy operation selection"],
    ["AtCoder","Greedy","D. Takahashi Unevolved","https://atcoder.jp/contests/abc180/tasks/abc180_d","Hard","Greedy evolution choice"],
    ["AtCoder","Greedy","A. Multiple Array","https://atcoder.jp/contests/agc009/tasks/agc009_a","Hard","Reverse greedy adjustment"],
    ["AtCoder","Greedy","E. Red and Green Apples","https://atcoder.jp/contests/abc160/tasks/abc160_e","Hard","Sort & select top K"],
    ["AtCoder","Greedy","D. Summer Vacation","https://atcoder.jp/contests/abc137/tasks/abc137_d","Hard","Sort by deadline & max heap"],
    ["AtCoder","Greedy","D. Patisserie ABC","https://atcoder.jp/contests/abc100/tasks/abc100_d","Hard","Multidimensional greedy"],
    ["AtCoder","Greedy","E. Amusement Park","https://atcoder.jp/contests/abc216/tasks/abc216_e","Hard","Priority queue greedy"],
    ["AtCoder","Greedy","D. Katana Thrower","https://atcoder.jp/contests/abc085/tasks/abc085_d","Hard","Greedy throw strategy"],
    ["AtCoder","Greedy","E. Wrapping Chocolate","https://atcoder.jp/contests/abc245/tasks/abc245_e","Hard","Sort & greedy matching"],
    ["AtCoder","Greedy","F. Bread","https://atcoder.jp/contests/abc252/tasks/abc252_f","Hard","Greedy Huffman-like merging"],
]
SPOJ = [
    ["SPOJ","Greedy","I AM VERY BUSY","https://www.spoj.com/problems/BUSYMAN/","Easy","Activity selection - sort by end time"],
    ["SPOJ","Greedy","CHOCOLA - Chocolate","https://www.spoj.com/problems/CHOCOLA/","Medium","Sort costs descending - greedy cut"],
    ["SPOJ","Greedy","Aggressive cows","https://www.spoj.com/problems/AGGRCOW/","Medium","Binary search + greedy placement"],
    ["SPOJ","Greedy","Wine trading in Gergovia","https://www.spoj.com/problems/GERGOVIA/","Medium","Two-pointer greedy balance"],
    ["SPOJ","Greedy","Expedition","https://www.spoj.com/problems/EXPEDI/","Medium","Max-heap greedy refueling"],
    ["SPOJ","Greedy","RENT - Rent your airplane","https://www.spoj.com/problems/RENT/","Medium","Weighted interval scheduling"],
    ["SPOJ","Greedy","BAISED - Biased Standings","https://www.spoj.com/problems/BAISED/","Easy","Sort & minimize absolute diff"],
    ["SPOJ","Greedy","BAT3 - BATMAN3","https://www.spoj.com/problems/BAT3/","Medium","Greedy LIS variant"],
    ["SPOJ","Greedy","DEFKIN - Defense of a Kingdom","https://www.spoj.com/problems/DEFKIN/","Easy","Max gap in rows & columns"],
    ["SPOJ","Greedy","FASHION - Fashion Shows","https://www.spoj.com/problems/FASHION/","Easy","Sort both arrays"],
    ["SPOJ","Greedy","EGYPIZZA - Egyptian Pizza","https://www.spoj.com/problems/EGYPIZZA/","Medium","Greedy pizza slicing"],
    ["SPOJ","Greedy","LAZYPROG - The lazy programmer","https://www.spoj.com/problems/LAZYPROG/","Medium","Deadline sorting + priority queue"],
    ["SPOJ","Greedy","GCJ101BB - Picking Up Chicks","https://www.spoj.com/problems/GCJ101BB/","Medium","Greedy counting from end"],
    ["SPOJ","Greedy","ARRANGE - Arranging Amplifiers","https://www.spoj.com/problems/ARRANGE/","Easy","Sort with special 1-handling"],
    ["SPOJ","Greedy","BYTESE2 - Two Seals","https://www.spoj.com/problems/BYTESE2/","Medium","Sort by area - greedy pack"],
    ["SPOJ","Greedy","GREED - Greedy island","https://www.spoj.com/problems/GREED/","Medium","Graph components + greedy swaps"],
    ["SPOJ","Greedy","DIEHARD - Die Hard","https://www.spoj.com/problems/DIEHARD/","Medium","Greedy state transitions"],
    ["SPOJ","Greedy","MSTICK - Musical Stick","https://www.spoj.com/problems/MSTICK/","Medium","Greedy ordering optimization"],
    ["SPOJ","Greedy","ABA12C - Buy Apples","https://www.spoj.com/problems/ABA12C/","Medium","Unbounded knapsack"],
    ["SPOJ","Greedy","ACPC10A - What's Next","https://www.spoj.com/problems/ACPC10A/","Easy","Greedy progression finder"],
    ["SPOJ","Greedy","ACPC11B - Between the Mountains","https://www.spoj.com/problems/ACPC11B/","Easy","Two-pointer greedy"],
    ["SPOJ","Greedy","HELP - Helping People","https://www.spoj.com/problems/HELP/","Medium","Greedy charity distribution"],
    ["SPOJ","Greedy","WTK - What's The Killer","https://www.spoj.com/problems/WTK/","Medium","Greedy probability strategy"],
    ["SPOJ","Greedy","HOTELS - Hotels Along the Coast","https://www.spoj.com/problems/HOTELS/","Easy","Two-pointer greedy window"],
    ["SPOJ","Greedy","AMR10G - Christmas Play","https://www.spoj.com/problems/AMR10G/","Easy","Sort sliding window min diff"],
    ["SPOJ","Greedy","SBANK - Sorting Bank","https://www.spoj.com/problems/SBANK/","Easy","Greedy string sorting"],
    ["SPOJ","Greedy","FACEFRND - Facebook Friends","https://www.spoj.com/problems/FACEFRND/","Easy","Greedy friend counting"],
]
HACKERRANK = [
    ["HackerRank","Greedy","Minimum Absolute Difference in an Array","https://www.hackerrank.com/challenges/minimum-absolute-difference-in-an-array/","Easy","Sort adjacent pairs"],
    ["HackerRank","Greedy","Marc's Cakewalk","https://www.hackerrank.com/challenges/marcs-cakewalk/","Easy","Sort descending"],
    ["HackerRank","Greedy","Grid Challenge","https://www.hackerrank.com/challenges/grid-challenge/","Easy","Sort each row & check columns"],
    ["HackerRank","Greedy","Luck Balance","https://www.hackerrank.com/challenges/luck-balance/","Easy","Sort important contests descending"],
    ["HackerRank","Greedy","Maximum Perimeter Triangle","https://www.hackerrank.com/challenges/maximum-perimeter-triangle/","Easy","Sort descending check triplets"],
    ["HackerRank","Greedy","Beautiful Pairs","https://www.hackerrank.com/challenges/beautiful-pairs/","Easy","Greedy frequency matching"],
    ["HackerRank","Greedy","Sherlock and The Beast","https://www.hackerrank.com/challenges/sherlock-and-the-beast/","Easy","Greedy digit construction"],
    ["HackerRank","Greedy","Priyanka and Toys","https://www.hackerrank.com/challenges/priyanka-and-toys/","Easy","Sort & greedy container fill"],
    ["HackerRank","Greedy","Largest Permutation","https://www.hackerrank.com/challenges/largest-permutation/","Easy","Swap largest to front greedily"],
    ["HackerRank","Greedy","Mark and Toys","https://www.hackerrank.com/challenges/mark-and-toys/","Easy","Sort ascending & buy"],
    ["HackerRank","Greedy","Two Arrays","https://www.hackerrank.com/challenges/two-arrays/","Easy","Sort one asc other desc"],
    ["HackerRank","Greedy","Jim and the Orders","https://www.hackerrank.com/challenges/jim-and-the-orders/","Easy","Sort by completion time"],
    ["HackerRank","Greedy","Permuting Two Arrays","https://www.hackerrank.com/challenges/permuting-two-arrays/","Easy","Sort one asc one desc"],
    ["HackerRank","Greedy","Chief Hopper","https://www.hackerrank.com/challenges/chief-hopper/","Medium","Reverse greedy energy calc"],
    ["HackerRank","Greedy","Greedy Florist","https://www.hackerrank.com/challenges/greedy-florist/","Medium","Sort descending & multiply by round"],
    ["HackerRank","Greedy","Max Min","https://www.hackerrank.com/challenges/angry-children/","Medium","Sort & sliding window"],
    ["HackerRank","Greedy","Candies","https://www.hackerrank.com/challenges/candies/","Medium","Left-to-right & right-to-left passes"],
    ["HackerRank","Greedy","Goodland Electricity","https://www.hackerrank.com/challenges/goodland-electricity/","Medium","Greedy rightmost coverage"],
    ["HackerRank","Greedy","Beautiful 3 Set","https://www.hackerrank.com/challenges/beautiful-3-set/","Hard","Greedy structured construction"],
    ["HackerRank","Greedy","Reverse Shuffle Merge","https://www.hackerrank.com/challenges/reverse-shuffle-merge/","Hard","Greedy character frequency"],
    ["HackerRank","Greedy","Accessory Collection","https://www.hackerrank.com/challenges/accessory-collection/","Hard","Greedy combinatorial buying"],
    ["HackerRank","Greedy","Burst Balloons","https://www.hackerrank.com/challenges/burst-balloons/","Hard","Greedy interval overlap"],
    ["HackerRank","Greedy","Team Formation","https://www.hackerrank.com/challenges/team-formation/","Medium","Greedy chain building"],
]
INTERVIEWBIT = [
    ["InterviewBit","Greedy Algorithm","Highest Product","https://www.interviewbit.com/problems/highest-product/","Easy","Sorting then max product of three"],
    ["InterviewBit","Greedy Algorithm","Bulbs","https://www.interviewbit.com/problems/bulbs/","Easy","State flip minimization"],
    ["InterviewBit","Greedy Algorithm","Disjoint Intervals","https://www.interviewbit.com/problems/disjoint-intervals/","Easy","Interval scheduling / earliest finish"],
    ["InterviewBit","Greedy Algorithm","Largest Permutation","https://www.interviewbit.com/problems/largest-permutation/","Easy","Greedy swap from largest to smallest"],
    ["InterviewBit","Greedy Algorithm","Meeting Rooms","https://www.interviewbit.com/problems/meeting-rooms/","Medium","Minimum platforms / interval overlap"],
    ["InterviewBit","Greedy Algorithm","Distribute Candy","https://www.interviewbit.com/problems/distribute-candy/","Medium","Left-right pass greedy"],
    ["InterviewBit","Greedy Algorithm","Seats","https://www.interviewbit.com/problems/seats/","Medium","Median-based gathering"],
    ["InterviewBit","Greedy Algorithm","Assign Mice to Holes","https://www.interviewbit.com/problems/assign-mice-to-holes/","Medium","Sort and match"],
    ["InterviewBit","Greedy Algorithm","Majority Element","https://www.interviewbit.com/problems/majority-element/","Medium","Boyer-Moore voting"],
    ["InterviewBit","Greedy Algorithm","Gas Station","https://www.interviewbit.com/problems/gas-station/","Medium","Circular tour / deficit tracking"],
]
HACKEREARTH = [
    ["HackerEarth","Basics of Greedy Algorithms","OrOasis","https://www.hackerearth.com/problem/algorithm/oroasis-7e736f17/","Medium","Interval scheduling"],
    ["HackerEarth","Basics of Greedy Algorithms","Equal Arrays","https://www.hackerearth.com/problem/algorithm/equal-arrays-b4f49bc1/","Medium","Array manipulation greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Not Even Max Sum","https://www.hackerearth.com/problem/algorithm/not-even-max-sum-a3ccf284/","Easy","Maximum sum selection"],
    ["HackerEarth","Basics of Greedy Algorithms","Bobs Quest","https://www.hackerearth.com/problem/algorithm/bobs-quest-d65227d1/","Medium","Greedy traversal"],
    ["HackerEarth","Basics of Greedy Algorithms","Swap Sum","https://www.hackerearth.com/problem/algorithm/swap-sum-786eb7eb/","Easy","Swap-based maximization"],
    ["HackerEarth","Basics of Greedy Algorithms","Signaling","https://www.hackerearth.com/problem/algorithm/signaling-07a313d7/","Easy","Range covering greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","DreamGrids Luxury Shopping","https://www.hackerearth.com/problem/algorithm/dreamgrids-luxury-shopping-07b2f274/","Medium","Sort by value knapsack"],
    ["HackerEarth","Basics of Greedy Algorithms","Empty Game","https://www.hackerearth.com/problem/algorithm/empty-game-d49730e1/","Easy","Greedy game strategy"],
    ["HackerEarth","Basics of Greedy Algorithms","Double Beauty","https://www.hackerearth.com/problem/algorithm/double-beauty-711a7ca1/","Easy","Digit-based greedy construction"],
    ["HackerEarth","Basics of Greedy Algorithms","Bob And The Tasks","https://www.hackerearth.com/problem/algorithm/bob-and-the-tasks-e3532635/","Hard","Task scheduling greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Bob And The Magic Count","https://www.hackerearth.com/problem/algorithm/bob-and-the-magic-count-d016bec6/","Easy","Counting with greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Too Chocolatey","https://www.hackerearth.com/problem/algorithm/too-chocolatey-232e97e0/","Easy","Chocolate distribution greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Operation with X","https://www.hackerearth.com/problem/algorithm/add-or-subtract-a43b7c14/","Hard","Greedy with add/subtract"],
    ["HackerEarth","Basics of Greedy Algorithms","Special Number","https://www.hackerearth.com/problem/algorithm/special-number-11-d5a1a96f/","Hard","Digit construction greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Split String","https://www.hackerearth.com/problem/algorithm/split-string-2-f088aa39/","Easy","String partitioning greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Legendary Magician","https://www.hackerearth.com/problem/algorithm/legendary-magician-64c50776/","Medium","Game strategy greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Closer","https://www.hackerearth.com/problem/algorithm/closer-142dd040/","Medium","Distance minimization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Maximum Operation Count","https://www.hackerearth.com/problem/algorithm/maximum-operation-count-8245cce4/","Medium","Operation count optimization"],
    ["HackerEarth","Basics of Greedy Algorithms","Minimum Score","https://www.hackerearth.com/problem/algorithm/minimum-score-1528c5c0/","Medium","Score minimization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Tree of Candles","https://www.hackerearth.com/problem/algorithm/tree-of-candles-912e495c/","Medium","Tree-based greedy selection"],
    ["HackerEarth","Basics of Greedy Algorithms","Fruit Slicing","https://www.hackerearth.com/problem/algorithm/fruit-slicing-9a455100/","Easy","Partition greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Safe Programming","https://www.hackerearth.com/problem/algorithm/safe-programming-d5cf9331/","Easy","Safety constraint greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Stay Healthy!","https://www.hackerearth.com/problem/algorithm/good-health-c0c56f5f/","Medium","Health resource allocation"],
    ["HackerEarth","Basics of Greedy Algorithms","Minimum Cost","https://www.hackerearth.com/problem/algorithm/minimum-cost-14-143d011a/","Easy","Cost minimization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Bob and the minimum string","https://www.hackerearth.com/problem/algorithm/bob-and-the-minimum-string-0443d2de/","Medium","Lexicographic minimization"],
    ["HackerEarth","Basics of Greedy Algorithms","Flip AB","https://www.hackerearth.com/problem/algorithm/flip-ab-26df82b3/","Medium","String flip minimization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Wesam and Omar","https://www.hackerearth.com/problem/algorithm/wesam-and-omar-e927dd23/","Easy","Game turn greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Alternative moves","https://www.hackerearth.com/problem/algorithm/alternative-moves-f12ee40a/","Easy","Move selection greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","A good array","https://www.hackerearth.com/problem/algorithm/savage-array-94706055/","Easy","Array construction greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Types of burgers","https://www.hackerearth.com/problem/algorithm/k-burgers-4d560710/","Medium","Burger resource allocation"],
    ["HackerEarth","Basics of Greedy Algorithms","Bobs empire","https://www.hackerearth.com/problem/algorithm/bob-empire-4955c35b/","Easy","Empire building greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","A dice tower","https://www.hackerearth.com/problem/algorithm/tower-c889471c/","Easy","Dice tower construction"],
    ["HackerEarth","Basics of Greedy Algorithms","The maximum value","https://www.hackerearth.com/problem/algorithm/array-maximum-01fc2734/","Easy","Max value selection"],
    ["HackerEarth","Basics of Greedy Algorithms","Beautiful numbers","https://www.hackerearth.com/problem/algorithm/beautiful-numbers-4-20d7065b/","Medium","Digit construction greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Sum of cards","https://www.hackerearth.com/problem/algorithm/card-sum-6710882a/","Easy","Card sum selection greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Three rectangles","https://www.hackerearth.com/problem/algorithm/3-rectangles-2-21ef0284/","Medium","Rectangle packing greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Bobs confusion","https://www.hackerearth.com/problem/algorithm/lucky-confusion-2c714d08/","Medium","Confusion minimization"],
    ["HackerEarth","Basics of Greedy Algorithms","Manhattan distance","https://www.hackerearth.com/problem/algorithm/manhattan-2fc15b93/","Easy","Distance minimization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Factors","https://www.hackerearth.com/problem/algorithm/factors-2-50c92a46/","Medium","Factor-based greedy selection"],
    ["HackerEarth","Basics of Greedy Algorithms","Team division","https://www.hackerearth.com/problem/algorithm/team-division-3f28e964/","Easy","Team splitting greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Operations on a tree","https://www.hackerearth.com/problem/algorithm/operation-on-tree-ae14ee70/","Hard","Tree operation greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Subtree swap","https://www.hackerearth.com/problem/algorithm/subtree-swap-f3734629/","Medium","Tree swap greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Average Subarray","https://www.hackerearth.com/problem/algorithm/average-subarray-7b376ebf/","Easy","Subarray average greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","A color box","https://www.hackerearth.com/problem/algorithm/paint-box-3e9796fd/","Easy","Color box greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Minimize nodes","https://www.hackerearth.com/problem/algorithm/minimize-nodes-15f14b04/","Hard","Node minimization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Meeting the origin","https://www.hackerearth.com/problem/algorithm/meet-at-origin-97c16088/","Easy","Distance minimization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","A special date","https://www.hackerearth.com/problem/algorithm/lucky-birth-date-fa83abfe/","Medium","Date-based greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Three problems","https://www.hackerearth.com/problem/algorithm/3-problems-5d1c956d/","Medium","Problem selection greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","The score game","https://www.hackerearth.com/problem/algorithm/score-game-fbf0cd0c/","Medium","Game score greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Likeable arrays","https://www.hackerearth.com/problem/algorithm/likeable-array-3e61d786/","Easy","Array likability greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Zero subarray","https://www.hackerearth.com/problem/algorithm/zero-subarray-8358c5d9/","Medium","Zero-sum greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Divide the digits","https://www.hackerearth.com/problem/algorithm/digits-divide-6f200dd9/","Easy","Digit division greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Smallest number","https://www.hackerearth.com/problem/algorithm/smallest-number-5-5b41ef1d/","Easy","Smallest number construction"],
    ["HackerEarth","Basics of Greedy Algorithms","A smallest number","https://www.hackerearth.com/problem/algorithm/smallest-number-4-7ee4ca9a/","Medium","Number construction greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Multiple of 3","https://www.hackerearth.com/problem/algorithm/multiple-85dda659/","Easy","Divisibility greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","XOR subsequences","https://www.hackerearth.com/problem/algorithm/xor-subsequence-2-d972bf76/","Easy","XOR-based greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Filling stones","https://www.hackerearth.com/problem/algorithm/filling-stones-078c792f/","Easy","Stone filling greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Divide arrays","https://www.hackerearth.com/problem/algorithm/divide-array-3-10ef1aae/","Easy","Array partition greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Equalize strings","https://www.hackerearth.com/problem/algorithm/string-equalizer-d4a539ba/","Easy","String equalization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","The weighted graph","https://www.hackerearth.com/problem/algorithm/weighted-graph-8e6b1122/","Medium","Graph weight greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","A bitwise pair","https://www.hackerearth.com/problem/algorithm/bitwise-pair-c50c40d8/","Easy","Bitwise pair greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","A XOR value","https://www.hackerearth.com/problem/algorithm/xor-value-6dc9d9e4/","Medium","XOR optimization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","The smallest string","https://www.hackerearth.com/problem/algorithm/smallest-string-2-e150a408/","Medium","String minimization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","The smallest permutation","https://www.hackerearth.com/problem/algorithm/smallest-permutation-5584d662/","Easy","Permutation greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Deleting arrays","https://www.hackerearth.com/problem/algorithm/array-deletion-2-aee9dffe/","Easy","Array deletion greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","A chessboard","https://www.hackerearth.com/problem/algorithm/chessboard-2-8f06e380/","Easy","Chessboard coloring greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Providing gifts","https://www.hackerearth.com/problem/algorithm/monotization-065bcc29/","Easy","Gift distribution greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","The maximum range","https://www.hackerearth.com/problem/algorithm/maximum-range-7cb6dd0c/","Easy","Range maximization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Maximum subsequences","https://www.hackerearth.com/problem/algorithm/maximal-subsequence-c9f19b0a/","Medium","Subsequence selection greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Unique sorting","https://www.hackerearth.com/problem/algorithm/unique-sorting-17d60d9f/","Easy","Sorting-based greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","An interesting game","https://www.hackerearth.com/problem/algorithm/interesting-game-4-b6515135/","Hard","Game theory greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Profits by cars","https://www.hackerearth.com/problem/algorithm/jetha-and-cars-2d835131/","Easy","Profit maximization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","The maximum number","https://www.hackerearth.com/problem/algorithm/max-num-eb15ff4f/","Medium","Number construction greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Changes in a string","https://www.hackerearth.com/problem/algorithm/ab-string-5f6b213a/","Easy","String change greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Destination cost","https://www.hackerearth.com/problem/algorithm/destination-cost-2b27f15b/","Easy","Cost minimization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Smallest chosen word","https://www.hackerearth.com/problem/algorithm/smallest-chosen-word-0108fd21/","Easy","Word selection greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Coprimes","https://www.hackerearth.com/problem/algorithm/coprimed-32042ef1/","Easy","Coprime selection greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Mosaics and holes","https://www.hackerearth.com/problem/algorithm/filip-kotinioo-39795217/","Easy","Pattern filling greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Subxor","https://www.hackerearth.com/problem/algorithm/subxor-e114a622/","Easy","XOR subarray greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Operations on an Array","https://www.hackerearth.com/problem/algorithm/operations-on-an-array-2187f48a/","Easy","Array operations greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Toy Box","https://www.hackerearth.com/problem/algorithm/toy-box-5044b3ed/","Easy","Toy distribution greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","An Easy Problem","https://www.hackerearth.com/problem/algorithm/an-easy-problem-1-47aac9ac/","Easy","Simple greedy selection"],
    ["HackerEarth","Basics of Greedy Algorithms","Array Modification","https://www.hackerearth.com/problem/algorithm/array-modification-4569e6e6/","Easy","Array modification greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Hectic Game","https://www.hackerearth.com/problem/algorithm/hectic-game-2e74ada4/","Easy","Game strategy greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Equal Division","https://www.hackerearth.com/problem/algorithm/division-of-salary-e495efbb/","Easy","Equal division greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Pikachu and the Game of Strings","https://www.hackerearth.com/problem/algorithm/pikachu-and-the-game-of-strings-1-8c22a8ce/","Easy","String game greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Binary Matrix","https://www.hackerearth.com/problem/algorithm/binary-matrix-1-d77d7d00/","Easy","Matrix flip greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Three Equal parts","https://www.hackerearth.com/problem/algorithm/threequal-parts-ecf91f02/","Medium","Array partition greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","One Swap to Palindrome","https://www.hackerearth.com/problem/algorithm/one-swap-to-palindrome-d96d4e21/","Easy","Palindrome by swap greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Maximize Array Sum","https://www.hackerearth.com/problem/algorithm/bob-and-profit-fd9f0ee3/","Easy","Sum maximization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Remove the element","https://www.hackerearth.com/problem/algorithm/harry-and-horcrux-1-df65f8e9/","Medium","Element removal greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Bob And GCD","https://www.hackerearth.com/problem/algorithm/bob-and-gcd-d6d86b3b/","Easy","GCD-based greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Architects Dilemma..!","https://www.hackerearth.com/problem/algorithm/problem-17-f8bc297f/","Easy","Architecture resource greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Mathison and the funny subarray","https://www.hackerearth.com/problem/algorithm/mathison-and-the-funny-substring-b3f58587/","Easy","Subarray selection greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Help..!!","https://www.hackerearth.com/problem/algorithm/help-1-0315faf6/","Medium","Assistance allocation greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Dexter and Points","https://www.hackerearth.com/problem/algorithm/dexter-and-points-39399feb/","Medium","Point selection greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","K Friends","https://www.hackerearth.com/problem/algorithm/k-friends-89908017/","Easy","Friend grouping greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Minimum Cabs","https://www.hackerearth.com/problem/algorithm/minimum-cabs-0798cfa5/","Easy","Interval cab allocation"],
    ["HackerEarth","Basics of Greedy Algorithms","Protect the Cities","https://www.hackerearth.com/problem/algorithm/protect-the-cities-1/","Easy","City protection range greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Cities and co-ordinates","https://www.hackerearth.com/problem/algorithm/protect-the-cities/","Easy","Coordinate-based greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Dorsplen","https://www.hackerearth.com/problem/algorithm/dorsplen/","Easy","Simple greedy selection"],
    ["HackerEarth","Basics of Greedy Algorithms","Exploring ruins","https://www.hackerearth.com/problem/algorithm/exploring-ruins/","Easy","Ruins exploration greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Eat Or Not?","https://www.hackerearth.com/problem/algorithm/eat-or-not-22/","Easy","Eat/not decision greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Mike and LMS","https://www.hackerearth.com/problem/algorithm/mike-and-lms/","Easy","LMS string greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Assorted Arrangement","https://www.hackerearth.com/problem/algorithm/assorted-arrangement-3/","Easy","Arrangement greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Milly and Chocolates IV","https://www.hackerearth.com/problem/algorithm/milly-and-chocolates-iv-6/","Easy","Chocolate distribution greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Taxi Please!","https://www.hackerearth.com/problem/algorithm/taxi-please/","Easy","Taxi allocation greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Tree tearing","https://www.hackerearth.com/problem/algorithm/tree-tearing-easy-contest/","Hard","Tree removal greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Arrays force","https://www.hackerearth.com/problem/algorithm/arrays-force-easy-contest/","Medium","Array force greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Easy Strong Permutation","https://www.hackerearth.com/problem/algorithm/easy-strong-permutation/","Easy","Permutation construction greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","In search of Samosa","https://www.hackerearth.com/problem/algorithm/in-search-of-samosa-pledge-easy-3/","Easy","Knapsack-like greedy selection"],
    ["HackerEarth","Basics of Greedy Algorithms","Arjit and Printing Press","https://www.hackerearth.com/problem/algorithm/arjit-and-printing-press/","Easy","Printing press greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Chandu and Consecutive Letters","https://www.hackerearth.com/problem/algorithm/chandu-and-consecutive-letters/","Easy","String deduplication greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Add - Subtract","https://www.hackerearth.com/problem/algorithm/add-subtract/","Easy","Add/subtract operation greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Sharpen the pencils","https://www.hackerearth.com/problem/algorithm/sharpen-the-pencils-2/","Easy","Pencil sharpening greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Fast Sort","https://www.hackerearth.com/problem/algorithm/fast-sort-1/","Easy","Sorting-based greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Raj and his Slippers","https://www.hackerearth.com/problem/algorithm/raj-his-slippers/","Easy","Slipper matching greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Hunger Games","https://www.hackerearth.com/problem/algorithm/hunger-games/","Easy","Game strategy greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Rooms","https://www.hackerearth.com/problem/algorithm/rooms-1/","Medium","Room allocation interval greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Swap It","https://www.hackerearth.com/problem/algorithm/swap-it-2/","Easy","Swap-based greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Little Jhool and his punishment","https://www.hackerearth.com/problem/algorithm/little-jhool-and-his-punishment/","Easy","Punishment minimization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Chandu and his toy stack","https://www.hackerearth.com/problem/algorithm/chandu-and-his-toy-stack/","Easy","Toy stacking greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Flip the World","https://www.hackerearth.com/problem/algorithm/flip-the-world/","Easy","Flip minimization greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Process Scheduling","https://www.hackerearth.com/problem/approximate/process-scheduling-34fa1bb3/","Hard","Process scheduling greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Shuffle Array","https://www.hackerearth.com/problem/approximate/shuffle-array-3df1e5bb/","Hard","Array shuffle greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Special Substring","https://www.hackerearth.com/problem/approximate/as-23d8d46d/","Hard","Substring selection greedy"],
    ["HackerEarth","Basics of Greedy Algorithms","Binary Sum","https://www.hackerearth.com/problem/approximate/binary-sum-2c11887a/","Hard","Binary sum greedy"],
]

LIGHTOJ = [
    ["LightOJ","Greedy","Brush (II)","https://lightoj.com/problem/brush-2","Medium","Sorting + Greedy Sweeping"],
    ["LightOJ","Greedy","Conquering Keokradong","https://lightoj.com/problem/conquering-keokradong","Medium","Binary Search + Greedy"],
    ["LightOJ","Greedy","Get the Containers","https://lightoj.com/problem/get-the-containers","Medium","Binary Search + Greedy"],
    ["LightOJ","Greedy","Old Sorting","https://lightoj.com/problem/old-sorting","Medium","Sorting + Greedy Swapping"],
    ["LightOJ","Greedy","Sum of Factorials","https://lightoj.com/problem/sum-of-factorials","Easy","Greedy Selection"],
    ["LightOJ","Greedy","Karate Competition","https://lightoj.com/problem/karate-competition","Medium","Greedy Matching"],
    ["LightOJ","Greedy","Mafia","https://lightoj.com/problem/mafia","Medium","Greedy Scheduling"],
    ["LightOJ","Greedy","Diagonal Sum","https://lightoj.com/problem/diagonal-sum","Hard","Greedy Construction"],
    ["LightOJ","Greedy","Monitoring Processes","https://lightoj.com/problem/monitoring-processes","Medium","Greedy Interval Scheduling"],
    ["LightOJ","Greedy","A Gift from the Setter","https://lightoj.com/problem/a-gift-from-the-setter","Medium","Sorting + Greedy"],
    ["LightOJ","Greedy","Binary Matrix (II)","https://lightoj.com/problem/binary-matrix-ii","Hard","Greedy Matrix Manipulation"],
    ["LightOJ","Greedy","Confusion in the Problemset","https://lightoj.com/problem/confusion-in-the-problemset","Medium","Greedy + Sorting"],
    ["LightOJ","Greedy","Underwater Snipers","https://lightoj.com/problem/underwater-snipers","Hard","Greedy + Binary Search"],
    ["LightOJ","Greedy","Scarecrow","https://lightoj.com/problem/scarecrow","Medium","Greedy Placement"],
    ["LightOJ","Greedy","Palindromic Numbers (III)","https://lightoj.com/problem/palindromic-numbers-iii","Medium","Greedy Digit Construction"],
    ["LightOJ","Greedy","The Monkey and the Oiled Bamboo","https://lightoj.com/problem/the-monkey-and-the-oiled-bamb","Medium","Binary Search + Greedy"],
    ["LightOJ","Huffman Coding","Restoring Middle Earth","https://lightoj.com/problem/restoring-middle-earth","Medium","Huffman Coding"],
    ["LightOJ","Greedy","Civil and Evil Engineer","https://lightoj.com/problem/civil-and-evil-engineer","Medium","Greedy (Kruskal Variant)"],
    ["LightOJ","Greedy","Donation","https://lightoj.com/problem/donation","Medium","Greedy (MST)"],
    ["LightOJ","Greedy","Road Construction","https://lightoj.com/problem/road-construction","Medium","Greedy (MST)"],
    ["LightOJ","Greedy","Secret Origins","https://lightoj.com/problem/secret-origins","Medium","Greedy Bit Manipulation"],
    ["LightOJ","Greedy","False Ordering","https://lightoj.com/problem/false-ordering","Medium","Greedy Sorting by Divisor Count"],
    ["LightOJ","Greedy","Boiled Eggs","https://lightoj.com/problem/boiled-eggs","Easy","Greedy Selection"],
    ["LightOJ","Greedy","Counting Triangles","https://lightoj.com/problem/counting-triangles","Medium","Greedy + Binary Search"],
]
TIMUS = [
    ["Timus","Greedy","Democracy in Danger","https://acm.timus.ru/problem.aspx?space=1&num=1025","Easy","Sorting + Greedy"],
    ["Timus","Greedy","Two Teams","https://acm.timus.ru/problem.aspx?space=1&num=1106","Medium","Bipartite Coloring + Greedy"],
    ["Timus","Greedy","Horns and Hoofs","https://acm.timus.ru/problem.aspx?space=1&num=1200","Medium","Enumeration + Greedy"],
    ["Timus","Greedy","Sequence Median","https://acm.timus.ru/problem.aspx?space=1&num=1306","Medium","Heap + Greedy"],
    ["Timus","Greedy","Monobilliards","https://acm.timus.ru/problem.aspx?space=1&num=1494","Medium","Stack/Greedy Simulation"],
    ["Timus","Greedy","Taxi","https://acm.timus.ru/problem.aspx?space=1&num=1607","Medium","Greedy Simulation"],
    ["Timus","Greedy","Cipher Message","https://acm.timus.ru/problem.aspx?space=1&num=1654","Medium","Stack + Greedy"],
    ["Timus","Greedy","Sandro's Book","https://acm.timus.ru/problem.aspx?space=1&num=1723","Easy","Greedy Counting"],
    ["Timus","Greedy","Lost in Localization","https://acm.timus.ru/problem.aspx?space=1&num=1785","Easy","Greedy Ranges"],
    ["Timus","Greedy","Ural Steaks","https://acm.timus.ru/problem.aspx?space=1&num=1820","Easy","Greedy Math"],
    ["Timus","Greedy","Psych Up's Eigenvalues","https://acm.timus.ru/problem.aspx?space=1&num=1880","Easy","Greedy Intersection"],
    ["Timus","Greedy","The battle near the swamp","https://acm.timus.ru/problem.aspx?space=1&num=1991","Medium","Greedy Counting"],
    ["Timus","Greedy","Mathematicians and Berries","https://acm.timus.ru/problem.aspx?space=1&num=2001","Easy","Simple Greedy"],
    ["Timus","Greedy","About Grisha N.","https://acm.timus.ru/problem.aspx?space=1&num=2012","Easy","Simple Math"],
    ["Timus","Greedy","Another Dress Rehearsal","https://acm.timus.ru/problem.aspx?space=1&num=2035","Medium","Greedy Construction"],
    ["Timus","Greedy","Simple Expression","https://acm.timus.ru/problem.aspx?space=1&num=2066","Easy","Greedy Selection"],
    ["Timus","Greedy","Flags","https://acm.timus.ru/problem.aspx?space=1&num=1225","Medium","Greedy Counting"],
    ["Timus","Greedy","Bookworm","https://acm.timus.ru/problem.aspx?space=1&num=1638","Medium","Greedy Math"],
    ["Timus","Greedy","1D Maze","https://acm.timus.ru/problem.aspx?space=1&num=1642","Medium","Greedy Simulation"],
    ["Timus","Greedy","Hide and Seek","https://acm.timus.ru/problem.aspx?space=1&num=1725","Medium","Greedy Strategy"],
    ["Timus","Greedy","Teamwork","https://acm.timus.ru/problem.aspx?space=1&num=1581","Easy","Greedy Counting"],
    ["Timus","Greedy","Eniya","https://acm.timus.ru/problem.aspx?space=1&num=1293","Easy","Simple Greedy"],
    ["Timus","Greedy","Two Gangsters","https://acm.timus.ru/problem.aspx?space=1&num=1409","Easy","Simple Greedy"],
    ["Timus","Greedy","Plato","https://acm.timus.ru/problem.aspx?space=1&num=2111","Medium","Greedy"],
]
CODINGNINJAS = [
    ["CodingNinjas","Greedy","Activity Selection","https://www.codingninjas.com/studio/problems/activity-selection_1090889","Easy","Greedy Selection"],
    ["CodingNinjas","Greedy","Fractional Knapsack","https://www.codingninjas.com/studio/problems/fractional-knapsack_1090888","Medium","Greedy by Ratio"],
    ["CodingNinjas","Greedy","N Meetings in One Room","https://www.codingninjas.com/studio/problems/n-meetings-in-one-room_1090887","Easy","Greedy by End Time"],
    ["CodingNinjas","Greedy","Job Sequencing Problem","https://www.codingninjas.com/studio/problems/job-sequencing-problem_1090886","Medium","Greedy + Sorting"],
    ["CodingNinjas","Greedy","Minimum Number of Platforms","https://www.codingninjas.com/studio/problems/minimum-number-of-platforms_1090885","Medium","Greedy + Sweeping"],
    ["CodingNinjas","Greedy","Coin Change Problem","https://www.codingninjas.com/studio/problems/coin-change-problem_1090884","Medium","Greedy Denominations"],
    ["CodingNinjas","Greedy","Huffman Coding","https://www.codingninjas.com/studio/problems/huffman-coding_1090883","Hard","Greedy Tree Building"],
    ["CodingNinjas","Greedy","Shop in Candy Store","https://www.codingninjas.com/studio/problems/shop-in-candy-store_1090882","Easy","Greedy Buying Strategy"],
    ["CodingNinjas","Greedy","Maximum trains for which stoppage can be provided","https://www.codingninjas.com/studio/problems/maximum-trains_1090881","Medium","Greedy Interval Selection"],
    ["CodingNinjas","Greedy","Minimum cost to cut board into squares","https://www.codingninjas.com/studio/problems/minimum-cost-to-cut-board-into-squares_1090880","Hard","Greedy with Priority Queue"],
    ["CodingNinjas","Greedy","Maximize sum of absolute difference","https://www.codingninjas.com/studio/problems/maximize-sum-of-absolute-difference_1090879","Medium","Sorting + Greedy"],
    ["CodingNinjas","Greedy","Check if it possible to survive on island","https://www.codingninjas.com/studio/problems/check-if-it-possible-to-survive-on-island_1090878","Medium","Greedy Simulation"],
    ["CodingNinjas","Greedy","Minimize the Heights II","https://www.codingninjas.com/studio/problems/minimize-the-heights-ii_1090877","Hard","Sorting + Greedy"],
    ["CodingNinjas","Greedy","Minimum number of Coins","https://www.codingninjas.com/studio/problems/minimum-number-of-coins_1090876","Easy","Greedy Denominations"],
    ["CodingNinjas","Greedy","Maximum sum after K negations","https://www.codingninjas.com/studio/problems/maximum-sum-after-k-negations_1090875","Easy","Sorting + Greedy"],
    ["CodingNinjas","Greedy","Choose and Swap","https://www.codingninjas.com/studio/problems/choose-and-swap_1090874","Medium","Greedy Character Selection"],
    ["CodingNinjas","Greedy","Find maximum meeting in one room","https://www.codingninjas.com/studio/problems/find-maximum-meeting-in-one-room_1090873","Easy","Greedy by End Time"],
]
BAELDUNG = [
    ["Baeldung","Greedy","Activity Selection Problem","https://www.baeldung.com/cs/activity-selection-problem","Medium","Interval Scheduling"],
    ["Baeldung","Greedy","Fractional Knapsack Problem","https://www.baeldung.com/java-knapsack","Medium","Greedy by Value/Weight Ratio"],
    ["Baeldung","Greedy","Huffman Coding","https://www.baeldung.com/java-huffman-coding","Hard","Greedy Prefix Code"],
    ["Baeldung","Greedy","Dijkstra's Algorithm","https://www.baeldung.com/java-dijkstra","Hard","Greedy Shortest Path"],
    ["Baeldung","Greedy","Prim's Algorithm","https://www.baeldung.com/java-prim-algorithm","Hard","Greedy MST"],
    ["Baeldung","Greedy","Kruskal's Algorithm","https://www.baeldung.com/java-kruskal-algorithm","Hard","Greedy MST"],
    ["Baeldung","Greedy","Coin Change Problem (Greedy)","https://www.baeldung.com/cs/coin-change-problem-greedy","Medium","Greedy Denominations"],
    ["Baeldung","Greedy","Interval Scheduling / Job Scheduling","https://www.baeldung.com/cs/interval-scheduling","Medium","Greedy by Finish Time"],
]
CPALGO = [
    ["CP-Algorithms","Greedy","Maximum Subarray Sum (Kadane)","https://cp-algorithms.com/others/maximum_average_segment.html","Medium","Kadane's Algorithm"],
    ["CP-Algorithms","Greedy","Scheduling Jobs on One Machine","https://cp-algorithms.com/schedules/schedule_one_machine.html","Hard","Sorting by Ratio (Greedy)"],
    ["CP-Algorithms","Greedy","Scheduling Jobs on Two Machines","https://cp-algorithms.com/schedules/schedule_two_machines.html","Hard","Johnson's Rule (Greedy)"],
    ["CP-Algorithms","Greedy","Optimal Schedule given Deadlines and Durations","https://cp-algorithms.com/schedules/schedule-with-completion-duration.html","Hard","Greedy + Priority Queue"],
    ["CP-Algorithms","Greedy","Kruskal's Algorithm (MST)","https://cp-algorithms.com/graph/mst_kruskal.html","Hard","Greedy Edge Selection"],
    ["CP-Algorithms","Greedy","Prim's Algorithm (MST)","https://cp-algorithms.com/graph/mst_prim.html","Hard","Greedy Vertex Selection"],
    ["CP-Algorithms","Greedy","Dijkstra's Algorithm","https://cp-algorithms.com/graph/dijkstra.html","Hard","Greedy Shortest Path"],
    ["CP-Algorithms","Greedy","Minimum-cost Flow","https://cp-algorithms.com/graph/min_cost_flow.html","Hard","Successive Shortest Path (Greedy)"],
]
ALGOEXPERT = [
    ["AlgoExpert","Greedy","Minimum Waiting Time","https://www.algoexpert.io/questions/minimum-waiting-time","Easy","Sorting + Greedy"],
    ["AlgoExpert","Greedy","Class Photos","https://www.algoexpert.io/questions/class-photos","Easy","Greedy Pairing"],
    ["AlgoExpert","Greedy","Tandem Bicycle","https://www.algoexpert.io/questions/tandem-bicycle","Easy","Greedy Pairing (Min/Max)"],
    ["AlgoExpert","Greedy","Non-Constructible Change","https://www.algoexpert.io/questions/non-constructible-change","Easy","Sorting + Greedy"],
    ["AlgoExpert","Greedy","Valid Starting City","https://www.algoexpert.io/questions/valid-starting-city","Medium","Greedy Simulation"],
    ["AlgoExpert","Greedy","Task Assignment","https://www.algoexpert.io/questions/task-assignment","Medium","Greedy Pairing"],
]
BINARYSEARCH = [
    ["BinarySearch","Greedy","Making Change (Coin Change)","https://binarysearch.com/problems/Making-Change","Medium","Greedy Denominations"],
    ["BinarySearch","Greedy","Task Scheduling","https://binarysearch.com/problems/Task-Scheduling","Medium","Greedy Interval Scheduling"],
    ["BinarySearch","Greedy","Activity Selection","https://binarysearch.com/problems/Activity-Selection","Medium","Greedy by Finish Time"],
    ["BinarySearch","Greedy","Minimum Number of Platforms","https://binarysearch.com/problems/Minimum-Number-of-Platforms","Medium","Greedy Sweeping"],
    ["BinarySearch","Greedy","Fractional Knapsack","https://binarysearch.com/problems/Fractional-Knapsack","Medium","Greedy by Ratio"],
    ["BinarySearch","Greedy","Job Sequencing","https://binarysearch.com/problems/Job-Sequencing","Medium","Greedy + Sorting"],
    ["BinarySearch","Greedy","Minimize Waiting Time","https://binarysearch.com/problems/Minimize-Waiting-Time","Easy","Sorting + Greedy"],
    ["BinarySearch","Greedy","Maximum Units on a Truck","https://binarysearch.com/problems/Maximum-Units-on-a-Truck","Medium","Sorting + Greedy"],
    ["BinarySearch","Greedy","Two City Scheduling","https://binarysearch.com/problems/Two-City-Scheduling","Medium","Greedy by Difference"],
    ["BinarySearch","Greedy","Minimum Cost to Connect Sticks","https://binarysearch.com/problems/Minimum-Cost-to-Connect-Sticks","Medium","Greedy + Min-Heap"],
    ["BinarySearch","Greedy","Partition Labels","https://binarysearch.com/problems/Partition-Labels","Medium","Greedy Interval Merging"],
    ["BinarySearch","Greedy","Remove Duplicate Letters","https://binarysearch.com/problems/Remove-Duplicate-Letters","Hard","Greedy + Stack"],
    ["BinarySearch","Greedy","Jump Game II","https://binarysearch.com/problems/Jump-Game-II","Medium","Greedy BFS"],
]
TOPCODER = [
    ["Topcoder","Greedy","GroceryBagger (SRM 222)","https://community.topcoder.com/stat?c=problem_statement&pm=3450&rd=5868","Easy","Greedy Packing"],
    ["Topcoder","Greedy","FanFailure (SRM 195)","https://community.topcoder.com/stat?c=problem_statement&pm=2235&rd=5070","Easy","Greedy Selection"],
    ["Topcoder","Greedy","PlayGame (SRM 217)","https://community.topcoder.com/stat?c=problem_statement&pm=3002&rd=5863","Medium","Greedy Strategy"],
    ["Topcoder","Greedy","SchoolAssembly (TCO04)","https://community.topcoder.com/stat?c=problem_statement&pm=1119&rd=5879","Medium","Greedy Construction"],
    ["Topcoder","Greedy","RockStar (SRM 216)","https://community.topcoder.com/stat?c=problem_statement&pm=2984&rd=5862","Medium","Greedy Counting"],
    ["Topcoder","Greedy","Apothecary (SRM 204)","https://community.topcoder.com/stat?c=problem_statement&pm=2312&rd=5850","Medium","Greedy Base Conversion"],
    ["Topcoder","Greedy","Boxing (TCO04 Round 3)","https://community.topcoder.com/stat?c=problem_statement&pm=2977&rd=5880","Medium","Greedy Scheduling"],
    ["Topcoder","Greedy","Unblur (TCO04 Semifinal)","https://community.topcoder.com/stat?c=problem_statement&pm=2945&rd=5884","Hard","Greedy Image Reconstruction"],
    ["Topcoder","Greedy","Crossroads (SRM 217)","https://community.topcoder.com/stat?c=problem_statement&pm=3042&rd=5863","Medium","Greedy Simulation"],
    ["Topcoder","Greedy","TCSocks (SRM 207)","https://community.topcoder.com/stat?c=problem_statement&pm=2894&rd=5853","Hard","Greedy Strategy"],
    ["Topcoder","Greedy","HeatDeath (TCO04 Round 4)","https://community.topcoder.com/stat?c=problem_statement&pm=2982&rd=5881","Hard","Greedy + Math"],
    ["Topcoder","Greedy","BioScore (TCO04 Semifinal)","https://community.topcoder.com/stat?c=problem_statement&pm=3038&rd=5882","Hard","Greedy Matrix Scoring"],
    ["Topcoder","Greedy","Rationalization (SRM 224)","https://community.topcoder.com/stat?c=problem_statement&pm=2347&rd=5870","Hard","Greedy Rationalization"],
    ["Topcoder","Greedy","GoldMine (SRM 169)","https://community.topcoder.com/stat?c=problem_statement&pm=1957&rd=4650","Hard","Greedy Worker Allocation"],
    ["Topcoder","Greedy","MLBRecord (TCO04 Round 2)","https://community.topcoder.com/stat?c=problem_statement&pm=2236&rd=5879","Hard","Greedy Simulation"],
    ["Topcoder","Greedy","RearrangeFurniture (SRM 220)","https://community.topcoder.com/stat?c=problem_statement&pm=3076&rd=5866","Hard","Greedy Cycle Decomposition"],
    ["Topcoder","Greedy","WorldPeace (SRM 204)","https://community.topcoder.com/stat?c=problem_statement&pm=2420&rd=5850","Hard","Greedy Group Formation"],
]

for src_name, rows in [
    ("AtCoder", ATCODER),
    ("SPOJ", SPOJ),
    ("HackerRank", HACKERRANK),
    ("InterviewBit", INTERVIEWBIT),
    ("HackerEarth", HACKEREARTH),
    ("LightOJ", LIGHTOJ),
    ("Timus", TIMUS),
    ("CodingNinjas", CODINGNINJAS),
    ("Baeldung", BAELDUNG),
    ("CP-Algorithms", CPALGO),
    ("AlgoExpert", ALGOEXPERT),
    ("BinarySearch", BINARYSEARCH),
    ("Topcoder", TOPCODER),
]:
    for r in rows:
        url = r[3].strip()
        if url and url not in all_rows:
            all_rows[url] = r

print(f"Total unique problems: {len(all_rows)}")
by_platform = {}
for r in all_rows.values():
    p = r[0]
    by_platform[p] = by_platform.get(p, 0) + 1
for p, c in sorted(by_platform.items(), key=lambda x: -x[1]):
    print(f"  {p}: {c}")

with open(OUTPUT, 'w', newline='', encoding='utf-8') as f:
    w = csv.writer(f)
    w.writerow(["Platform","Category","Problem Name","URL","Difficulty","Key Concept"])
    for url in sorted(all_rows.keys()):
        w.writerow(all_rows[url])

print(f"\nWritten to {OUTPUT}")
