/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as PatternsIndexRouteImport } from './routes/patterns.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as ProblemsTopicRouteImport } from './routes/problems.$topic'
import { Route as PatternsPatternRouteImport } from './routes/patterns.$pattern'
import { Route as LearnPatternsRouteImport } from './routes/learn.patterns'
import { Route as LearnTrackRouteImport } from './routes/learn.$track'
import { Route as LearnPatternRouteImport } from './routes/learn.$pattern'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsIndexRoute = PatternsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatternsRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsTopicRoute = ProblemsTopicRouteImport.update({
  id: '/problems/$topic',
  path: '/problems/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsPatternRoute = PatternsPatternRouteImport.update({
  id: '/$pattern',
  path: '/$pattern',
  getParentRoute: () => PatternsRoute,
} as any)
const LearnPatternsRoute = LearnPatternsRouteImport.update({
  id: '/learn/patterns',
  path: '/learn/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTrackRoute = LearnTrackRouteImport.update({
  id: '/learn/$track',
  path: '/learn/$track',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPatternRoute = LearnPatternRouteImport.update({
  id: '/learn/$pattern',
  path: '/learn/$pattern',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/patterns': typeof PatternsRouteWithChildren
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/learn/$pattern': typeof LearnPatternRoute
  '/learn/$track': typeof LearnTrackRoute
  '/learn/patterns': typeof LearnPatternsRoute
  '/patterns/$pattern': typeof PatternsPatternRoute
  '/problems/$topic': typeof ProblemsTopicRoute
  '/learn/': typeof LearnIndexRoute
  '/patterns/': typeof PatternsIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/learn/$pattern': typeof LearnPatternRoute
  '/learn/$track': typeof LearnTrackRoute
  '/learn/patterns': typeof LearnPatternsRoute
  '/patterns/$pattern': typeof PatternsPatternRoute
  '/problems/$topic': typeof ProblemsTopicRoute
  '/learn': typeof LearnIndexRoute
  '/patterns': typeof PatternsIndexRoute
  '/problems': typeof ProblemsIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/patterns': typeof PatternsRouteWithChildren
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/learn/$pattern': typeof LearnPatternRoute
  '/learn/$track': typeof LearnTrackRoute
  '/learn/patterns': typeof LearnPatternsRoute
  '/patterns/$pattern': typeof PatternsPatternRoute
  '/problems/$topic': typeof ProblemsTopicRoute
  '/learn/': typeof LearnIndexRoute
  '/patterns/': typeof PatternsIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/explore'
    | '/patterns'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/learn/$pattern'
    | '/learn/$track'
    | '/learn/patterns'
    | '/patterns/$pattern'
    | '/problems/$topic'
    | '/learn/'
    | '/patterns/'
    | '/problems/'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/explore'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/learn/$pattern'
    | '/learn/$track'
    | '/learn/patterns'
    | '/patterns/$pattern'
    | '/problems/$topic'
    | '/learn'
    | '/patterns'
    | '/problems'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/explore'
    | '/patterns'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/learn/$pattern'
    | '/learn/$track'
    | '/learn/patterns'
    | '/patterns/$pattern'
    | '/problems/$topic'
    | '/learn/'
    | '/patterns/'
    | '/problems/'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExploreRoute: typeof ExploreRoute
  PatternsRoute: typeof PatternsRouteWithChildren
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  LearnPatternRoute: typeof LearnPatternRoute
  LearnTrackRoute: typeof LearnTrackRoute
  LearnPatternsRoute: typeof LearnPatternsRoute
  ProblemsTopicRoute: typeof ProblemsTopicRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/': {
      id: '/patterns/'
      path: '/'
      fullPath: '/patterns/'
      preLoaderRoute: typeof PatternsIndexRouteImport
      parentRoute: typeof PatternsRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$topic': {
      id: '/problems/$topic'
      path: '/problems/$topic'
      fullPath: '/problems/$topic'
      preLoaderRoute: typeof ProblemsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/$pattern': {
      id: '/patterns/$pattern'
      path: '/$pattern'
      fullPath: '/patterns/$pattern'
      preLoaderRoute: typeof PatternsPatternRouteImport
      parentRoute: typeof PatternsRoute
    }
    '/learn/patterns': {
      id: '/learn/patterns'
      path: '/learn/patterns'
      fullPath: '/learn/patterns'
      preLoaderRoute: typeof LearnPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$track': {
      id: '/learn/$track'
      path: '/learn/$track'
      fullPath: '/learn/$track'
      preLoaderRoute: typeof LearnTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$pattern': {
      id: '/learn/$pattern'
      path: '/learn/$pattern'
      fullPath: '/learn/$pattern'
      preLoaderRoute: typeof LearnPatternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PatternsRouteChildren {
  PatternsPatternRoute: typeof PatternsPatternRoute
  PatternsIndexRoute: typeof PatternsIndexRoute
}

const PatternsRouteChildren: PatternsRouteChildren = {
  PatternsPatternRoute: PatternsPatternRoute,
  PatternsIndexRoute: PatternsIndexRoute,
}

const PatternsRouteWithChildren = PatternsRoute._addFileChildren(
  PatternsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExploreRoute: ExploreRoute,
  PatternsRoute: PatternsRouteWithChildren,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  LearnPatternRoute: LearnPatternRoute,
  LearnTrackRoute: LearnTrackRoute,
  LearnPatternsRoute: LearnPatternsRoute,
  ProblemsTopicRoute: ProblemsTopicRoute,
  LearnIndexRoute: LearnIndexRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
