/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as PatternRouteImport } from './routes/pattern'
import { Route as GeometryBookRouteImport } from './routes/geometry-book'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as PatternsIndexRouteImport } from './routes/patterns.index'
import { Route as PatternIndexRouteImport } from './routes/pattern.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as GeometryBookIndexRouteImport } from './routes/geometry-book.index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as ProblemsTopicRouteImport } from './routes/problems.$topic'
import { Route as PatternsPatternRouteImport } from './routes/patterns.$pattern'
import { Route as PatternSlugRouteImport } from './routes/pattern.$slug'
import { Route as LearnPatternsRouteImport } from './routes/learn.patterns'
import { Route as LearnTrackRouteImport } from './routes/learn.$track'
import { Route as LearnPatternRouteImport } from './routes/learn.$pattern'
import { Route as GeometryBookChapterSlugRouteImport } from './routes/geometry-book.$chapterSlug'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as BooksBookSlugRouteImport } from './routes/books.$bookSlug'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternRoute = PatternRouteImport.update({
  id: '/pattern',
  path: '/pattern',
  getParentRoute: () => rootRouteImport,
} as any)
const GeometryBookRoute = GeometryBookRouteImport.update({
  id: '/geometry-book',
  path: '/geometry-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsIndexRoute = PatternsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatternsRoute,
} as any)
const PatternIndexRoute = PatternIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatternRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeometryBookIndexRoute = GeometryBookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GeometryBookRoute,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const ProblemsTopicRoute = ProblemsTopicRouteImport.update({
  id: '/problems/$topic',
  path: '/problems/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsPatternRoute = PatternsPatternRouteImport.update({
  id: '/$pattern',
  path: '/$pattern',
  getParentRoute: () => PatternsRoute,
} as any)
const PatternSlugRoute = PatternSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PatternRoute,
} as any)
const LearnPatternsRoute = LearnPatternsRouteImport.update({
  id: '/learn/patterns',
  path: '/learn/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTrackRoute = LearnTrackRouteImport.update({
  id: '/learn/$track',
  path: '/learn/$track',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPatternRoute = LearnPatternRouteImport.update({
  id: '/learn/$pattern',
  path: '/learn/$pattern',
  getParentRoute: () => rootRouteImport,
} as any)
const GeometryBookChapterSlugRoute = GeometryBookChapterSlugRouteImport.update({
  id: '/$chapterSlug',
  path: '/$chapterSlug',
  getParentRoute: () => GeometryBookRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookSlugRoute = BooksBookSlugRouteImport.update({
  id: '/$bookSlug',
  path: '/$bookSlug',
  getParentRoute: () => BooksRoute,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRouteWithChildren
  '/explore': typeof ExploreRoute
  '/geometry-book': typeof GeometryBookRouteWithChildren
  '/pattern': typeof PatternRouteWithChildren
  '/patterns': typeof PatternsRouteWithChildren
  '/books/$bookSlug': typeof BooksBookSlugRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/geometry-book/$chapterSlug': typeof GeometryBookChapterSlugRoute
  '/learn/$pattern': typeof LearnPatternRoute
  '/learn/$track': typeof LearnTrackRoute
  '/learn/patterns': typeof LearnPatternsRoute
  '/pattern/$slug': typeof PatternSlugRoute
  '/patterns/$pattern': typeof PatternsPatternRoute
  '/problems/$topic': typeof ProblemsTopicRoute
  '/books/': typeof BooksIndexRoute
  '/geometry-book/': typeof GeometryBookIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/pattern/': typeof PatternIndexRoute
  '/patterns/': typeof PatternsIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/books/$bookSlug': typeof BooksBookSlugRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/geometry-book/$chapterSlug': typeof GeometryBookChapterSlugRoute
  '/learn/$pattern': typeof LearnPatternRoute
  '/learn/$track': typeof LearnTrackRoute
  '/learn/patterns': typeof LearnPatternsRoute
  '/pattern/$slug': typeof PatternSlugRoute
  '/patterns/$pattern': typeof PatternsPatternRoute
  '/problems/$topic': typeof ProblemsTopicRoute
  '/books': typeof BooksIndexRoute
  '/geometry-book': typeof GeometryBookIndexRoute
  '/learn': typeof LearnIndexRoute
  '/pattern': typeof PatternIndexRoute
  '/patterns': typeof PatternsIndexRoute
  '/problems': typeof ProblemsIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRouteWithChildren
  '/explore': typeof ExploreRoute
  '/geometry-book': typeof GeometryBookRouteWithChildren
  '/pattern': typeof PatternRouteWithChildren
  '/patterns': typeof PatternsRouteWithChildren
  '/books/$bookSlug': typeof BooksBookSlugRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/geometry-book/$chapterSlug': typeof GeometryBookChapterSlugRoute
  '/learn/$pattern': typeof LearnPatternRoute
  '/learn/$track': typeof LearnTrackRoute
  '/learn/patterns': typeof LearnPatternsRoute
  '/pattern/$slug': typeof PatternSlugRoute
  '/patterns/$pattern': typeof PatternsPatternRoute
  '/problems/$topic': typeof ProblemsTopicRoute
  '/books/': typeof BooksIndexRoute
  '/geometry-book/': typeof GeometryBookIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/pattern/': typeof PatternIndexRoute
  '/patterns/': typeof PatternsIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/books'
    | '/explore'
    | '/geometry-book'
    | '/pattern'
    | '/patterns'
    | '/books/$bookSlug'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/geometry-book/$chapterSlug'
    | '/learn/$pattern'
    | '/learn/$track'
    | '/learn/patterns'
    | '/pattern/$slug'
    | '/patterns/$pattern'
    | '/problems/$topic'
    | '/books/'
    | '/geometry-book/'
    | '/learn/'
    | '/pattern/'
    | '/patterns/'
    | '/problems/'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/explore'
    | '/books/$bookSlug'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/geometry-book/$chapterSlug'
    | '/learn/$pattern'
    | '/learn/$track'
    | '/learn/patterns'
    | '/pattern/$slug'
    | '/patterns/$pattern'
    | '/problems/$topic'
    | '/books'
    | '/geometry-book'
    | '/learn'
    | '/pattern'
    | '/patterns'
    | '/problems'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/books'
    | '/explore'
    | '/geometry-book'
    | '/pattern'
    | '/patterns'
    | '/books/$bookSlug'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/geometry-book/$chapterSlug'
    | '/learn/$pattern'
    | '/learn/$track'
    | '/learn/patterns'
    | '/pattern/$slug'
    | '/patterns/$pattern'
    | '/problems/$topic'
    | '/books/'
    | '/geometry-book/'
    | '/learn/'
    | '/pattern/'
    | '/patterns/'
    | '/problems/'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BooksRoute: typeof BooksRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  GeometryBookRoute: typeof GeometryBookRouteWithChildren
  PatternRoute: typeof PatternRouteWithChildren
  PatternsRoute: typeof PatternsRouteWithChildren
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  LearnPatternRoute: typeof LearnPatternRoute
  LearnTrackRoute: typeof LearnTrackRoute
  LearnPatternsRoute: typeof LearnPatternsRoute
  ProblemsTopicRoute: typeof ProblemsTopicRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern': {
      id: '/pattern'
      path: '/pattern'
      fullPath: '/pattern'
      preLoaderRoute: typeof PatternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geometry-book': {
      id: '/geometry-book'
      path: '/geometry-book'
      fullPath: '/geometry-book'
      preLoaderRoute: typeof GeometryBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/': {
      id: '/patterns/'
      path: '/'
      fullPath: '/patterns/'
      preLoaderRoute: typeof PatternsIndexRouteImport
      parentRoute: typeof PatternsRoute
    }
    '/pattern/': {
      id: '/pattern/'
      path: '/'
      fullPath: '/pattern/'
      preLoaderRoute: typeof PatternIndexRouteImport
      parentRoute: typeof PatternRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geometry-book/': {
      id: '/geometry-book/'
      path: '/'
      fullPath: '/geometry-book/'
      preLoaderRoute: typeof GeometryBookIndexRouteImport
      parentRoute: typeof GeometryBookRoute
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/problems/$topic': {
      id: '/problems/$topic'
      path: '/problems/$topic'
      fullPath: '/problems/$topic'
      preLoaderRoute: typeof ProblemsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/$pattern': {
      id: '/patterns/$pattern'
      path: '/$pattern'
      fullPath: '/patterns/$pattern'
      preLoaderRoute: typeof PatternsPatternRouteImport
      parentRoute: typeof PatternsRoute
    }
    '/pattern/$slug': {
      id: '/pattern/$slug'
      path: '/$slug'
      fullPath: '/pattern/$slug'
      preLoaderRoute: typeof PatternSlugRouteImport
      parentRoute: typeof PatternRoute
    }
    '/learn/patterns': {
      id: '/learn/patterns'
      path: '/learn/patterns'
      fullPath: '/learn/patterns'
      preLoaderRoute: typeof LearnPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$track': {
      id: '/learn/$track'
      path: '/learn/$track'
      fullPath: '/learn/$track'
      preLoaderRoute: typeof LearnTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$pattern': {
      id: '/learn/$pattern'
      path: '/learn/$pattern'
      fullPath: '/learn/$pattern'
      preLoaderRoute: typeof LearnPatternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geometry-book/$chapterSlug': {
      id: '/geometry-book/$chapterSlug'
      path: '/$chapterSlug'
      fullPath: '/geometry-book/$chapterSlug'
      preLoaderRoute: typeof GeometryBookChapterSlugRouteImport
      parentRoute: typeof GeometryBookRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookSlug': {
      id: '/books/$bookSlug'
      path: '/$bookSlug'
      fullPath: '/books/$bookSlug'
      preLoaderRoute: typeof BooksBookSlugRouteImport
      parentRoute: typeof BooksRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BooksRouteChildren {
  BooksBookSlugRoute: typeof BooksBookSlugRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookSlugRoute: BooksBookSlugRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface GeometryBookRouteChildren {
  GeometryBookChapterSlugRoute: typeof GeometryBookChapterSlugRoute
  GeometryBookIndexRoute: typeof GeometryBookIndexRoute
}

const GeometryBookRouteChildren: GeometryBookRouteChildren = {
  GeometryBookChapterSlugRoute: GeometryBookChapterSlugRoute,
  GeometryBookIndexRoute: GeometryBookIndexRoute,
}

const GeometryBookRouteWithChildren = GeometryBookRoute._addFileChildren(
  GeometryBookRouteChildren,
)

interface PatternRouteChildren {
  PatternSlugRoute: typeof PatternSlugRoute
  PatternIndexRoute: typeof PatternIndexRoute
}

const PatternRouteChildren: PatternRouteChildren = {
  PatternSlugRoute: PatternSlugRoute,
  PatternIndexRoute: PatternIndexRoute,
}

const PatternRouteWithChildren =
  PatternRoute._addFileChildren(PatternRouteChildren)

interface PatternsRouteChildren {
  PatternsPatternRoute: typeof PatternsPatternRoute
  PatternsIndexRoute: typeof PatternsIndexRoute
}

const PatternsRouteChildren: PatternsRouteChildren = {
  PatternsPatternRoute: PatternsPatternRoute,
  PatternsIndexRoute: PatternsIndexRoute,
}

const PatternsRouteWithChildren = PatternsRoute._addFileChildren(
  PatternsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BooksRoute: BooksRouteWithChildren,
  ExploreRoute: ExploreRoute,
  GeometryBookRoute: GeometryBookRouteWithChildren,
  PatternRoute: PatternRouteWithChildren,
  PatternsRoute: PatternsRouteWithChildren,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  LearnPatternRoute: LearnPatternRoute,
  LearnTrackRoute: LearnTrackRoute,
  LearnPatternsRoute: LearnPatternsRoute,
  ProblemsTopicRoute: ProblemsTopicRoute,
  LearnIndexRoute: LearnIndexRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
